name: Create Release

on: release

jobs:
  create-release-artifact:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Build using Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install pip --upgrade pip
          pip install flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install flask
          pip install RPi.GPIO

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      #- name: run unit tests [pytest]
      #  run: pytest

      #- name: create build artifact [sdist]
      #  run: python setup.py sdist

      #- name: get release name
      #  id: get_release_name
      #  run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      #- name: upload build artifact
      #  uses: actions/upload-artifact@v2
      #  with:
      #    name: slidiy-${{ steps.get_release_name.outputs.VERSION }}
      #    path: dist/*
